mod commands;
mod db;
mod models;
mod services;
mod state;
mod utils;

#[cfg(test)]
mod tests;

use commands::{
    auth_commands::*, backup_commands::*, category_commands::*, customer_commands::*,
    expense_commands::*, invoice_payment_commands::*, payment_commands::*, product_commands::*,
    purchase_commands::*, purchase_return_commands::*, quotation_commands::*, report_commands::*,
    sales_commands::*, settings_commands::*, settlement_commands::*, supplier_commands::*,
};
use state::AppState;

pub fn run() {
    let app_state = AppState::initialize().expect("failed to initialize application state");
    let _ = services::backup_service::create_automatic_backup_if_due(app_state.db_path());

    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .manage(app_state)
        .invoke_handler(tauri::generate_handler![
            has_admin,
            setup_admin,
            login_admin,
            logout_admin,
            change_admin_password,
            get_current_admin,
            create_category,
            update_category,
            archive_category,
            restore_category,
            delete_category,
            list_categories,
            create_product,
            update_product,
            cancel_stock_adjustment,
            restore_stock_adjustment,
            permanently_delete_stock_adjustment,
            archive_product,
            restore_product,
            delete_product,
            get_product,
            list_products,
            generate_product_sku,
            get_product_stock,
            get_product_movement,
            list_supplier_variants,
            adjust_stock,
            create_supplier,
            update_supplier,
            archive_supplier,
            restore_supplier,
            delete_supplier,
            get_supplier,
            list_suppliers,
            get_supplier_statement,
            save_supplier_logo,
            get_supplier_logo,
            remove_supplier_logo,
            create_customer,
            update_customer,
            archive_customer,
            restore_customer,
            delete_customer,
            get_customer,
            list_customers,
            get_customer_statement,
            create_purchase_invoice,
            cancel_purchase_invoice,
            restore_purchase_invoice,
            permanently_delete_purchase_invoice,
            get_purchase_invoice,
            list_purchase_invoices,
            print_purchase_invoice,
            get_purchase_return_context,
            get_purchase_return,
            create_purchase_return,
            update_purchase_return,
            cancel_purchase_return,
            restore_purchase_return,
            print_purchase_return,
            create_sales_invoice,
            cancel_sales_invoice,
            restore_sales_invoice,
            permanently_delete_sales_invoice,
            get_sales_invoice,
            list_sales_invoices,
            print_sales_invoice,
            create_quotation,
            update_quotation,
            get_quotation,
            list_quotations,
            change_quotation_status,
            delete_quotation,
            convert_quotation,
            print_quotation,
            list_expense_categories,
            create_expense,
            update_expense,
            delete_expense,
            restore_expense,
            permanently_delete_expense,
            list_expenses,
            list_expense_payments,
            record_expense_payment,
            list_invoice_payments,
            record_invoice_payment,
            create_payment,
            delete_payment,
            restore_payment,
            permanently_delete_payment,
            list_payments,
            get_dashboard_summary,
            get_daily_sales_report,
            get_profit_report,
            get_monthly_profit_report,
            get_stock_report,
            get_stock_movement_report,
            get_low_stock_report,
            get_customer_debt_report,
            get_supplier_debt_report,
            get_expense_report,
            get_purchase_report,
            get_payment_report,
            get_inventory_value_report,
            get_best_selling_products_report,
            get_stock_count_report,
            get_cheapest_supplier_report,
            get_supplier_settlement_report,
            get_supplier_settlement_summary,
            create_settlement_payment,
            delete_settlement_payment,
            restore_settlement_payment,
            permanently_delete_settlement_payment,
            list_settlement_payments,
            get_company_settings,
            update_company_settings,
            save_company_logo,
            get_company_logo,
            remove_company_logo,
            clear_all_data,
            create_manual_backup,
            restore_backup,
            list_backups
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
