INSERT INTO company_settings (
    id,
    company_name,
    phone,
    email,
    address,
    tax_number,
    default_currency,
    invoice_prefix_sales,
    invoice_prefix_purchase,
    allow_negative_stock,
    backup_path,
    default_tax_rate,
    default_profit_method,
    created_at,
    updated_at
)
VALUES (
    1,
    'Steel Inventory Company',
    '',
    '',
    '',
    '',
    'USD',
    'SI',
    'PI',
    0,
    NULL,
    0,
    'snapshot',
    datetime('now'),
    datetime('now')
);

INSERT INTO expense_categories (name, description, is_active, created_at, updated_at) VALUES
('Rent', 'Office, warehouse, or shop rent', 1, datetime('now'), datetime('now')),
('Electricity', 'Electricity and utilities', 1, datetime('now'), datetime('now')),
('Fuel', 'Fuel and vehicle expenses', 1, datetime('now'), datetime('now')),
('Delivery', 'Delivery and transportation expenses', 1, datetime('now'), datetime('now')),
('Salary', 'Staff salary payments', 1, datetime('now'), datetime('now')),
('Maintenance', 'General maintenance expenses', 1, datetime('now'), datetime('now')),
('Tools', 'Tools and equipment expenses', 1, datetime('now'), datetime('now')),
('Packaging', 'Packaging material expenses', 1, datetime('now'), datetime('now')),
('Other', 'Other business expenses', 1, datetime('now'), datetime('now'));

INSERT INTO categories (id, name, parent_id, description, is_active, created_at, updated_at) VALUES
(1, 'Steel Products', NULL, 'Steel inventory root category', 1, datetime('now'), datetime('now')),
(2, 'Pipes', 1, NULL, 1, datetime('now'), datetime('now')),
(3, 'Galvanized Pipes', 2, NULL, 1, datetime('now'), datetime('now')),
(4, 'Square Pipes', 3, NULL, 1, datetime('now'), datetime('now')),
(5, 'Rectangular Pipes', 3, NULL, 1, datetime('now'), datetime('now')),
(6, 'Round Pipes', 3, NULL, 1, datetime('now'), datetime('now')),
(7, 'Black Pipes', 2, NULL, 1, datetime('now'), datetime('now')),
(8, 'Sheets / Plates', 1, NULL, 1, datetime('now'), datetime('now')),
(9, 'Galvanized Sheets', 8, NULL, 1, datetime('now'), datetime('now')),
(10, 'Black Sheets', 8, NULL, 1, datetime('now'), datetime('now')),
(11, 'Stainless Steel Sheets', 8, NULL, 1, datetime('now'), datetime('now')),
(12, 'Bars', 1, NULL, 1, datetime('now'), datetime('now')),
(13, 'Flat Bars', 12, NULL, 1, datetime('now'), datetime('now')),
(14, 'Round Bars', 12, NULL, 1, datetime('now'), datetime('now')),
(15, 'Square Bars', 12, NULL, 1, datetime('now'), datetime('now')),
(16, 'Angles / Channels / Beams', 1, NULL, 1, datetime('now'), datetime('now')),
(17, 'Angle Bar', 16, NULL, 1, datetime('now'), datetime('now')),
(18, 'U Channel', 16, NULL, 1, datetime('now'), datetime('now')),
(19, 'I Beam', 16, NULL, 1, datetime('now'), datetime('now')),
(20, 'H Beam', 16, NULL, 1, datetime('now'), datetime('now')),
(21, 'Rebar', 1, NULL, 1, datetime('now'), datetime('now')),
(22, 'Accessories', 1, NULL, 1, datetime('now'), datetime('now')),
(23, 'Equipment', 1, NULL, 1, datetime('now'), datetime('now'));
